-- Document context card
--
-- Adds a semantic "where does this document fit" card generated by an LLM
-- after extraction completes. The card is a high-signal summary used by
-- retrieval to give the chat model document-level context on top of
-- chunk-level search hits. See src/lib/context-card.ts for the shape and
-- the generator, and src/lib/document-processing.ts for how it's wired.
--
-- Shape (enforced in application code, not DB):
--   {
--     "summary_en":         string,
--     "summary_ar":         string | null,
--     "topics":             string[],
--     "key_parties":        string[],
--     "key_obligations":    string[],
--     "key_dates":          string[],
--     "document_role":      string,
--     "fits_with_projects": string[],   -- project UUIDs
--     "fit_rationale":      string,
--     "generated_at":       ISO 8601 timestamp,
--     "model":              string      -- e.g. "gpt-4o-mini"
--   }

alter table public.documents
  add column if not exists context_card jsonb;

-- Optional: GIN index for querying by topic / party without full scan.
-- Cheap to add now, trivial to drop later.
create index if not exists documents_context_card_gin
  on public.documents using gin (context_card);
