-- Briefing cache on workspace_profile.
--
-- The landing page briefing (see src/lib/daily-briefing.ts) is
-- regenerated by a gpt-4o-mini call per page load. At single-user
-- volume that's pennies per month, but the VC opens the app many
-- times per day and waiting on an LLM call for every refresh feels
-- slow. Cache the generated payload on workspace_profile (which
-- is already a singleton with id='default') and skip the LLM call
-- when the cache is fresh enough.
--
-- Two columns:
--   briefing_cache          jsonb     — the full DailyBriefing payload
--   briefing_generated_at   timestamptz — when it was produced
--
-- TTL is enforced in application code (src/lib/daily-briefing.ts)
-- rather than in SQL — the threshold may change as we tune, and
-- a plain column is easier to bust manually by setting it to null.

alter table public.workspace_profile
  add column if not exists briefing_cache jsonb;

alter table public.workspace_profile
  add column if not exists briefing_generated_at timestamptz;
